### ISSUE TITLE
What is the purpose of "file[:-2] not in mfi_source" in the build.py script?

### ISSUE THREAD

**Issue by tatleung** [Brawrdon/esp-homekit-arduino-sdk#4]
@Brawrdon,

First, thank you for publishing the library.  I think it will be great help for me and others.

I am working on HomeKit device that will be using the "espidf" framework instead of "arduino".  The project is using PlatformIO.  I make some changes to the library.json file and build.py script and able to compile my code.  In line 32 of the build.py script, there is a check for ```file[-2] not in mfi_source```.  What is the purpose of this check?  I had to remove this condition to make it to work with the espidf framework and would like to understand what impact it will have with this change.  I am planning to eventually migrate to the MFI version of the ESP HomeKit library and not sure if "mfi_source" is needed then.

```python
31:        for file in filenames:
32:            if file.endswith(".c") or file.endswith(".h") and file[:-2] not in mfi_source:
33:                shutil.move(dirpath + "/" + file, "lib/")
```

Thanks

**Comment by Brawrdon** [comment]
I'm really glad you're finding this project useful, it means a lot to me! 😄 

My thought process was to skip adding MFI source files (`esp_mfi_auth.c`, `esp_mfi_coprocessor.c`, etc.). It would check that the file name (without the trailing `.c` or `.h`) was inside the MFI source folder and ignore it. I think I was having build issues but solved them with another problem and accidentally kept this line in since the `mfi_source` variable isn't actually defined anywhere. This is why we install a linter everyone! 😅 

I'm not exactly sure how or why it fixed your problem. I planned to properly check out MFI versions of the SDK at a later date since I wasn't sure if what I was doing would keep the SDK compatible with the complaint version.

If you want to use this library but you're using the ESP-IDF framework, I recommend sticking with the original and adding the components to your project especially if you plan to migrate to the MFI complaint version. You can see how to do that with PlatformIO here: [https://docs.platformio.org/en/latest/frameworks/espidf.html#esp-idf-components](https://docs.platformio.org/en/latest/frameworks/espidf.html#esp-idf-components). Basically you just copy each folder inside the `components` directory of the SDK into the `components` directory of your project, PlatfromIO should pick them up and build them as normal.

Would you mind sharing what changes you made to the `library.json` and `build.py` files, I'm curious to see what you had to do to get that to work.

**Comment by tatleung** [comment]
@Brawrdon,

Thanks for the quick reply.  The change to ```library.json``` is very minor.  I updated the value for frameworks to an array and added "espidf" to the list of values:

```json
"frameworks": ["arduino", "espidf"],
```

Also, I will take a more detail looks at the reference document you suggested.  But in my first look, the process seems to be more manual setup than if the library is a PlatformIO compatible library.

Thanks,

**Comment by Brawrdon** [comment]
Aaah I see, well I'm glad it works the same!

Just be wary that (when I find the time and energy) I'll be adding Arduino style APIs that'll wrap over the ESP-IDF methods. They may or may not cause the ESP-IDF version to fail, it depends on if I need to add Arduino specific libraries. If that happens, you could still just use the extract the `build.py` into your project instead of using the entire library.
