### ISSUE TITLE
Version of esp-idf should be used?

### ISSUE THREAD

**Issue by beckmx** [Brawrdon/esp-homekit-arduino-sdk#6]
I tried using the library with platformio, it compiles flawlessly, and looks like it starts but seems that when it should really start the homekit service it just reboots due to an issue:
```
WiFi connected
IP address:
192.168.86.71
␛[1;37mKeystore initialised␛[0m
␛[1;37mAccessory is not Paired with any controller␛[0m
␛[1;37mDatabase initialised. Accessory Device ID: XXXXXXXX4␛[0m
␛[1;37mHAP Initialization succeeded. Version : 4.0-040b0f3␛[0m
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400da935  PS      : 0x00060830  A0      : 0x800daa64  A1      : 0x3ffdc640
A2      : 0x3ffb00d0  A3      : 0x3ffe7408  A4      : 0x3ffe711c  A5      : 0x3ffdc9ac
A6      : 0x00000041  A7      : 0x00000067  A8      : 0x800da935  A9      : 0x3ffdc620
A10     : 0x00000000  A11     : 0x3f4d01f0  A12     : 0x0000000c  A13     : 0x3ffdc2a0
A14     : 0x00000002  A15     : 0x3ffdc4a0  SAR     : 0x00000010  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000010  LBEG    : 0x40098c49  LEND    : 0x40098c6d  LCOUNT  : 0x800dd61e
```
I suspect is because of the  esp-idf version, which I was using:
`https://github.com/espressif/arduino-esp32.git#idf-release/v4.0`

Great library btw, it's the only one compiling so far

**Comment by Brawrdon** [comment]
I'm glad the library is what you're looking for! 😄

From my understanding, the original SDK was built for ESP-IDF 4.x.x though whilst creating the script the ESP32 Arduino framework I was using was 3.x.x. Since the actual code hasn't changed, I assume it would be more compatible with the version you're using than the one I built it against.

That being said, if you could decode the exception so we can see where the error is being through. This should help: [https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#filters](https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html#filters).

Also, could you post a bit of your code after the initialisation so we can take a look at that as well!
